### ISSUE TITLE
关于coco配置文件的参数设置

### ISSUE THREAD

**Issue by Penguin0321** [kongyan66/Gaofen-challenge#1]
你好，你的代码在configs/yolov8/yolov8_s_syncbn_fast_8xb16-500e_coco.py中修改了训练集路径等相关参数，但num_classes仍使用的是该文件初始的值80，而数据集预处理的代码中显示的类别数应该为7或者37，请问你在训练时使用的配置文件有修改num_classes吗

**Comment by kongyan66** [comment]
是的，这个需要根据实际比赛数据集的类别数量更改
