### ISSUE TITLE
数据下载链接

### ISSUE THREAD

**Issue by PGSmall** [kongyan66/Gaofen-challenge#2]
非常棒的比赛总结！您好，数据[google drive](https://drive.google.com/drive/folders/1VI-9jHOkcnOFf_Cw5feA5GCi3ndf3Ogf?usp=sharing)现在好像打不开了。如果您有空的话，可以更新下载链接吗？十分感谢！
Email: peigsh@njust.edu.cn

**Comment by kongyan66** [comment]
数据集是组委会提供的 参赛选手才可以获取  参赛的话可以找组委会获取哈

**Comment by PGSmall** [comment]
谢谢您的回复。
